### ISSUE TITLE
Failure to build using rustc 1.65.0

### ISSUE THREAD

**Issue by dmicsa** [kurtlawrence/papyrus#108]
Hi,

I'm new to rust I install rust on my machine, with an Win10 64 and tried to follow the instalation process running:
rustup toolchain add nightly
cargo +nightly install papyrus

It errors out with the message:
error[E0463]: can't find crate for `rustc_ast`
  --> C:\Users\Dan\.cargo\registry\src\github.com-1ecc6299db9ec823\racer-2.2.2\src/racer/lib.rs:16:1
   |
16 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_ast_pretty`
  --> C:\Users\Dan\.cargo\registry\src\github.com-1ecc6299db9ec823\racer-2.2.2\src/racer/lib.rs:17:1
   |
17 | extern crate rustc_ast_pretty;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
   = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `rustc_data_structures`
  --> C:\Users\Dan\.cargo\registry\src\github.com-1ecc6299db9ec823\racer-2.2.2\src/racer/lib.rs:18:1
   |
18 | extern crate rustc_data_structures;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
   |
...

**Comment by rvadaga** [comment]
Seeing the same issue! Despite installing the suggested rustup components
