### ISSUE TITLE
Syn Version Seems Wrong

### ISSUE THREAD

**Issue by mlucy** [kurtlawrence/papyrus#100]
Hi,

I tried installing this following the instructions on https://docs.rs/papyrus/0.17.1/papyrus/ , and I got a compilation error.  It seems like the code doesn't work with Syn 1.0.58.  I changed the syn dependency locally to specify `version = "=1.0.57"` and it worked for me.

I also found this Reddit comment, which suggests that the problem is Syn pushed a semver-violating update: https://www.reddit.com/r/rust/comments/kr64qz/nushell_025_now_with_custom_commands_variables/gi95a7t/

**Comment by kurtlawrence** [comment]
Hi @mlucy,
This project is not in active maintenance right now, but if you'd like to open PR that fixes this issue I can merge it in.
